### ISSUE TITLE
Build errors - Dictionary, JSONObject 

### ISSUE THREAD

**Issue by brianarnold789** [kiarnold/RiskSimlutator#27]
Dictionary and JSONObject cannot be resolved to a type
org.json not added to repo
not sure what 'Dictionary' object is required

**Comment by kiarnold** [comment]
Is this still in there? I looked (briefly) and didn't see these. I had added dictionary and then changed it to hashtable. And I got a different version of json just because I found much better examples and was starting to work through it. But I thought I added those to the classpath etc.

**Comment by brianarnold789** [comment]
I will update again when I get home and get back to you.
